name       : libglvnd
version    : 1.0.0
release    : 1
source     :
    - https://github.com/NVIDIA/libglvnd/archive/v1.0.0.tar.gz : d1cb238081f8fc708178f21e7e6b33a009c0807eae7a11b790146043f6e8eea5
homepage   : https://github.com/NVIDIA/libglvnd
license    :
    - MIT
    - GPL-2.0
    - BSD-3-Clause
summary    :
    - The GL Vendor-Neutral Dispatch library
component  :
    - xorg.display
description: |
    libglvnd is a vendor-neutral dispatch layer for arbitrating OpenGL API calls between multiple vendors. It allows multiple drivers from different vendors to coexist on the same filesystem, and determines which vendor to dispatch each API call to at runtime.
emul32     : yes
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - pkgconfig32(glproto)
setup      : |
    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
