name       : libglvnd
version    : 1.3.2
release    : 11
source     :
    - https://github.com/NVIDIA/libglvnd/archive/v1.3.2.tar.gz : 6f41ace909302e6a063fd9dc04760b391a25a670ba5f4b6edf9e30f21410b673
homepage   : https://github.com/NVIDIA/libglvnd
license    :
    - MIT
    - GPL-2.0
    - BSD-3-Clause
component  : xorg.display
summary    :
    - The GL Vendor-Neutral Dispatch library
description: |
    libglvnd is a vendor-neutral dispatch layer for arbitrating OpenGL API calls between multiple vendors. It allows multiple drivers from different vendors to coexist on the same filesystem, and determines which vendor to dispatch each API call to at runtime.
emul32     : yes
optimize   :
    - speed
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
patterns   :
    - /usr/lib64/lib*.so
    - 32bit : /usr/lib32/lib*.so
setup      : |
    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
