name       : libglvnd
version    : 1.3.1
release    : 9
source     :
    - https://github.com/NVIDIA/libglvnd/archive/v1.3.1.tar.gz : 787434966cd138d1685595e1ec64655665045067fd541e0002a0ecbf6bc3962c
homepage   : https://github.com/NVIDIA/libglvnd
license    :
    - MIT
    - GPL-2.0
    - BSD-3-Clause
summary    :
    - The GL Vendor-Neutral Dispatch library
component  :
    - xorg.display
description: |
    libglvnd is a vendor-neutral dispatch layer for arbitrating OpenGL API calls between multiple vendors. It allows multiple drivers from different vendors to coexist on the same filesystem, and determines which vendor to dispatch each API call to at runtime.
emul32     : yes
optimize   :
    - no-bind-now
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - pkgconfig32(glproto)
patterns   :
    - /usr/lib64/lib*.so
    - 32bit : /usr/lib32/lib*.so
setup      : |
    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
